### ISSUE TITLE
Support ASP Identity V2 for ASP MVC 4.6.2

### ISSUE THREAD

**Issue by papyr** [jonwagner/Insight.Database.Schema#56]
Hi I want to use insight for my app, can you please tell me if there ASP MVC identity support

Also is there sql dependency like changes tracker directly to C# objects.
Datatable audits as well
I can also help with Admin UI, if I understand this.

thanks

**Comment by pbolduc** [comment]
I do not think this is the correct project for those kind of activities.  If you would like to have provider to interact with the ASP.NET Identity, you could look at [Insight.Database](https://github.com/jonwagner/Insight.Database).  However, since Microsoft provides an Entity Framework interface already, there is nothing stopping you from using EF for the ASP.NET Identity and  [Insight.Database](https://github.com/jonwagner/Insight.Database) for your other code.

Database Audits: what are looking for in this area?

**Comment by Maarten88** [comment]
Some time ago I implemented an AspNet Identity UserStore connected to an existing sql database (with pre-existing custom tables for user) using Insight.Database and Insight.Database.Schema. Some Poc Code for it is here: https://github.com/Maarten88/Insight.Playground. It worked well.

**Comment by jonwagner** [comment]
If you have the sql for an identity provider, you can install it with this project, but I don't expect this to become a general sql generation tool.
